<?xml version="1.0"?>
<package format="3">
  <name>turtlebot3_msgs</name>
  <version>0.1.0</version>
  <description>DRL services for TurtleBot3 (DrlStep, Goal, RingGoal).</description>
  <maintainer email="kaushikraghupathruni@gmail.com">kaushik</maintainer>
  <license>Apache 2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>rosidl_default_generators</buildtool_depend>   <!-- generates the .srv code -->
  <depend>builtin_interfaces</depend>                              <!-- standard field types -->
  <exec_depend>rosidl_default_runtime</exec_depend>               <!-- lets nodes use the types at runtime -->
  <member_of_group>rosidl_interface_packages</member_of_group>    <!-- marks this as an interface pkg -->

  <export><build_type>ament_cmake</build_type></export>
</package>
